// src/pages/DataKaryawan.js
// eslint-disable-next-line no-unused-vars
import React, { useState, useEffect } from "react";
import DataTable from "react-data-table-component";
import "./Data.css";
import { FaEdit } from "react-icons/fa";
import { FaTrash } from "react-icons/fa";
import axios from "axios";

const DataKaryawan = () => {
  const customStyles = {
    headCells: {
      style: {
        backgroundColor: "#1E63B2",
        color: "white",
        fontWeight: "bold",
        borderBottom: "2px solid #0056b3",
        borderRight: "2px solid gray",
        display: "flex",
        justifyContent: "center",
      },
    },
    cells: {
      style: {
        borderRight: "2px solid #ddd",
        display: "flex",
        justifyContent: "center",
      },
    },
  };

  const columns = [
    { name: "No.", selector: (row) => row.no, sortable: true },
    { name: "Foto", selector: (row) => row.foto, sortable: true },
    {
      name: "Nama",
      selector: (row) => row.nama,
      sortable: true,
      style: {
        position: "sticky",
        left: "0",
        zIndex: 1,
        backgroundColor: "white",
      },
      cell: (row) => (
        <div className="flex justify-start items-center w-full">{row.nama}</div>
      ),
    },
    { name: "NIP/REG", selector: (row) => row.nip, sortable: true },
    { name: "Bidang", selector: (row) => row.bidang, sortable: true },
    { name: "Sub Bidang", selector: (row) => row.subBidang, sortable: true },
    { name: "Jabatan", selector: (row) => row.jabatan, sortable: true },
    { name: "Golongan/Ruang", selector: (row) => row.golRuang, sortable: true },
    { name: "Jenjang", selector: (row) => row.jenjang, sortable: true },
    { name: "Jenis", selector: (row) => row.jenis, sortable: true },
    {
      name: "Jenis Kelamin",
      selector: (row) => row.jenisKelamin,
      sortable: true,
    },
    {
      name: "Tempat Lahir",
      selector: (row) => row.tempatLahir,
      sortable: true,
    },
    {
      name: "Tanggal Lahir",
      selector: (row) => row.tanggalLahir,
      sortable: true,
    },
    { name: "Umur", selector: (row) => row.umur, sortable: true },
    { name: "NIK", selector: (row) => row.nik, sortable: true },
    { name: "NPWP", selector: (row) => row.npwp, sortable: true },
    { name: "No. Rek.", selector: (row) => row.noRek, sortable: true },
    { name: "No. KK", selector: (row) => row.noKK, sortable: true },
    { name: "Gol. Darah", selector: (row) => row.golDarah, sortable: true },
    { name: "No. HP", selector: (row) => row.noHP, sortable: true },
    { name: "Email", selector: (row) => row.email, sortable: true },
    { name: "Email Gov", selector: (row) => row.emailGov, sortable: true },
    { name: "Pendidikan", selector: (row) => row.pendidikan, sortable: true },
    { name: "Jurusan", selector: (row) => row.jurusan, sortable: true },
    { name: "Tahun Tamat", selector: (row) => row.tahunTamat, sortable: true },
    { name: "Jalan", selector: (row) => row.jalan, sortable: true },
    { name: "Desa", selector: (row) => row.desa, sortable: true },
    { name: "Kecamatan", selector: (row) => row.kecamatan, sortable: true },
    {
      name: "Kabupaten/Kota",
      selector: (row) => row.kabupatenKota,
      sortable: true,
    },
    { name: "Alamat", selector: (row) => row.alamat, sortable: true },
    {
      name: "Tahun SK Awal",
      selector: (row) => row.tahunSKAwal,
      sortable: true,
    },
    {
      name: "Tahun SK Akhir",
      selector: (row) => row.tahunSKAkhir,
      sortable: true,
    },
    { name: "Masa Kerja", selector: (row) => row.masaKerja, sortable: true },
    { name: "No. Reg. BKN", selector: (row) => row.noRegBKN, sortable: true },
    { name: "Jenis Tekon", selector: (row) => row.jenisTekon, sortable: true },
    {
      name: "Kelas Jabatan",
      selector: (row) => row.kelasJabatan,
      sortable: true,
    },
  ];

  useEffect(() => {
    const fetchData = async () => {
      axios.get("http://localhost:3000/employees/")
      .then(res => setRecords(res.data))
      .catch(err => console.log(err));
    };
    fetchData();
  }, []);

  // const data = [
  //   {
  //     id: 1,
  //     no: 1,
  //     foto: "Foto1",
  //     nama: "John Doe",
  //     nip: "123456789",
  //     bidang: "IT",
  //     subBidang: "Development",
  //     jabatan: "Manager",
  //     golRuang: "IV/a",
  //     jenjang: "S1",
  //     jenis: "PNS",
  //     jenisKelamin: "Laki-laki",
  //     tempatLahir: "Jakarta",
  //     tanggalLahir: "1990-01-01",
  //     umur: 34,
  //     nik: "1234567890123456",
  //     npwp: "01.234.567.8-901.000",
  //     noRek: "1234567890",
  //     noKK: "1234567890123456",
  //     golDarah: "A",
  //     noHP: "08123456789",
  //     email: "john.doe@example.com",
  //     emailGov: "john.doe@gov.com",
  //     pendidikan: "S1",
  //     jurusan: "Informatika",
  //     tahunTamat: 2012,
  //     jalan: "Jl. Merdeka",
  //     desa: "Desa Maju",
  //     kecamatan: "Kecamatan Sejahtera",
  //     kabupatenKota: "Kota Makmur",
  //     alamat: "Jl. Merdeka No. 1",
  //     tahunSKAwal: 2013,
  //     tahunSKAkhir: 2023,
  //     masaKerja: "10 Tahun",
  //     noRegBKN: "1234567890",
  //     jenisTekon: "Tekon A",
  //     kelasJabatan: "Kelas 1",
  //   },
  //   {
  //     id: 2,
  //     no: 2,
  //     foto: "Foto2",
  //     nama: "Jane Smith",
  //     nip: "987654321",
  //     bidang: "HR",
  //     subBidang: "Recruitment",
  //     jabatan: "Staff",
  //     golRuang: "III/b",
  //     jenjang: "S1",
  //     jenis: "PNS",
  //     jenisKelamin: "Perempuan",
  //     tempatLahir: "Bandung",
  //     tanggalLahir: "1992-05-15",
  //     umur: 32,
  //     nik: "6543210987654321",
  //     npwp: "09.876.543.2-109.000",
  //     noRek: "0987654321",
  //     noKK: "6543210987654321",
  //     golDarah: "B",
  //     noHP: "08987654321",
  //     email: "jane.smith@example.com",
  //     emailGov: "jane.smith@gov.com",
  //     pendidikan: "S1",
  //     jurusan: "Psikologi",
  //     tahunTamat: 2014,
  //     jalan: "Jl. Kebangsaan",
  //     desa: "Desa Sejahtera",
  //     kecamatan: "Kecamatan Maju",
  //     kabupatenKota: "Kota Damai",
  //     alamat: "Jl. Kebangsaan No. 2",
  //     tahunSKAwal: 2015,
  //     tahunSKAkhir: 2025,
  //     masaKerja: "8 Tahun",
  //     noRegBKN: "0987654321",
  //     jenisTekon: "Tekon B",
  //     kelasJabatan: "Kelas 2",
  //   },
  //   {
  //     id: 3,
  //     no: 3,
  //     foto: "Foto1",
  //     nama: "John Doe",
  //     nip: "123456789",
  //     bidang: "IT",
  //     subBidang: "Development",
  //     jabatan: "Manager",
  //     golRuang: "IV/a",
  //     jenjang: "S1",
  //     jenis: "PNS",
  //     jenisKelamin: "Laki-laki",
  //     tempatLahir: "Jakarta",
  //     tanggalLahir: "1990-01-01",
  //     umur: 34,
  //     nik: "1234567890123456",
  //     npwp: "01.234.567.8-901.000",
  //     noRek: "1234567890",
  //     noKK: "1234567890123456",
  //     golDarah: "A",
  //     noHP: "08123456789",
  //     email: "john.doe@example.com",
  //     emailGov: "john.doe@gov.com",
  //     pendidikan: "S1",
  //     jurusan: "Informatika",
  //     tahunTamat: 2012,
  //     jalan: "Jl. Merdeka",
  //     desa: "Desa Maju",
  //     kecamatan: "Kecamatan Sejahtera",
  //     kabupatenKota: "Kota Makmur",
  //     alamat: "Jl. Merdeka No. 1",
  //     tahunSKAwal: 2013,
  //     tahunSKAkhir: 2023,
  //     masaKerja: "10 Tahun",
  //     noRegBKN: "1234567890",
  //     jenisTekon: "Tekon A",
  //     kelasJabatan: "Kelas 1",
  //   },
  //   {
  //     id: 4,
  //     no: 4,
  //     foto: "Foto2",
  //     nama: "Jane Smith",
  //     nip: "987654321",
  //     bidang: "HR",
  //     subBidang: "Recruitment",
  //     jabatan: "Staff",
  //     golRuang: "III/b",
  //     jenjang: "S1",
  //     jenis: "PNS",
  //     jenisKelamin: "Perempuan",
  //     tempatLahir: "Bandung",
  //     tanggalLahir: "1992-05-15",
  //     umur: 32,
  //     nik: "6543210987654321",
  //     npwp: "09.876.543.2-109.000",
  //     noRek: "0987654321",
  //     noKK: "6543210987654321",
  //     golDarah: "B",
  //     noHP: "08987654321",
  //     email: "jane.smith@example.com",
  //     emailGov: "jane.smith@gov.com",
  //     pendidikan: "S1",
  //     jurusan: "Psikologi",
  //     tahunTamat: 2014,
  //     jalan: "Jl. Kebangsaan",
  //     desa: "Desa Sejahtera",
  //     kecamatan: "Kecamatan Maju",
  //     kabupatenKota: "Kota Damai",
  //     alamat: "Jl. Kebangsaan No. 2",
  //     tahunSKAwal: 2015,
  //     tahunSKAkhir: 2025,
  //     masaKerja: "8 Tahun",
  //     noRegBKN: "0987654321",
  //     jenisTekon: "Tekon B",
  //     kelasJabatan: "Kelas 2",
  //   },
  //   {
  //     id: 5,
  //     no: 5,
  //     foto: "Foto1",
  //     nama: "John Doe",
  //     nip: "123456789",
  //     bidang: "IT",
  //     subBidang: "Development",
  //     jabatan: "Manager",
  //     golRuang: "IV/a",
  //     jenjang: "S1",
  //     jenis: "PNS",
  //     jenisKelamin: "Laki-laki",
  //     tempatLahir: "Jakarta",
  //     tanggalLahir: "1990-01-01",
  //     umur: 34,
  //     nik: "1234567890123456",
  //     npwp: "01.234.567.8-901.000",
  //     noRek: "1234567890",
  //     noKK: "1234567890123456",
  //     golDarah: "A",
  //     noHP: "08123456789",
  //     email: "john.doe@example.com",
  //     emailGov: "john.doe@gov.com",
  //     pendidikan: "S1",
  //     jurusan: "Informatika",
  //     tahunTamat: 2012,
  //     jalan: "Jl. Merdeka",
  //     desa: "Desa Maju",
  //     kecamatan: "Kecamatan Sejahtera",
  //     kabupatenKota: "Kota Makmur",
  //     alamat: "Jl. Merdeka No. 1",
  //     tahunSKAwal: 2013,
  //     tahunSKAkhir: 2023,
  //     masaKerja: "10 Tahun",
  //     noRegBKN: "1234567890",
  //     jenisTekon: "Tekon A",
  //     kelasJabatan: "Kelas 1",
  //   },
  //   {
  //     id: 6,
  //     no: 6,
  //     foto: "Foto2",
  //     nama: "Jane Smith",
  //     nip: "987654321",
  //     bidang: "HR",
  //     subBidang: "Recruitment",
  //     jabatan: "Staff",
  //     golRuang: "III/b",
  //     jenjang: "S1",
  //     jenis: "PNS",
  //     jenisKelamin: "Perempuan",
  //     tempatLahir: "Bandung",
  //     tanggalLahir: "1992-05-15",
  //     umur: 32,
  //     nik: "6543210987654321",
  //     npwp: "09.876.543.2-109.000",
  //     noRek: "0987654321",
  //     noKK: "6543210987654321",
  //     golDarah: "B",
  //     noHP: "08987654321",
  //     email: "jane.smith@example.com",
  //     emailGov: "jane.smith@gov.com",
  //     pendidikan: "S1",
  //     jurusan: "Psikologi",
  //     tahunTamat: 2014,
  //     jalan: "Jl. Kebangsaan",
  //     desa: "Desa Sejahtera",
  //     kecamatan: "Kecamatan Maju",
  //     kabupatenKota: "Kota Damai",
  //     alamat: "Jl. Kebangsaan No. 2",
  //     tahunSKAwal: 2015,
  //     tahunSKAkhir: 2025,
  //     masaKerja: "8 Tahun",
  //     noRegBKN: "0987654321",
  //     jenisTekon: "Tekon B",
  //     kelasJabatan: "Kelas 2",
  //   },
  //   {
  //     id: 7,
  //     no: 7,
  //     foto: "Foto1",
  //     nama: "John Doe",
  //     nip: "123456789",
  //     bidang: "IT",
  //     subBidang: "Development",
  //     jabatan: "Manager",
  //     golRuang: "IV/a",
  //     jenjang: "S1",
  //     jenis: "PNS",
  //     jenisKelamin: "Laki-laki",
  //     tempatLahir: "Jakarta",
  //     tanggalLahir: "1990-01-01",
  //     umur: 34,
  //     nik: "1234567890123456",
  //     npwp: "01.234.567.8-901.000",
  //     noRek: "1234567890",
  //     noKK: "1234567890123456",
  //     golDarah: "A",
  //     noHP: "08123456789",
  //     email: "john.doe@example.com",
  //     emailGov: "john.doe@gov.com",
  //     pendidikan: "S1",
  //     jurusan: "Informatika",
  //     tahunTamat: 2012,
  //     jalan: "Jl. Merdeka",
  //     desa: "Desa Maju",
  //     kecamatan: "Kecamatan Sejahtera",
  //     kabupatenKota: "Kota Makmur",
  //     alamat: "Jl. Merdeka No. 1",
  //     tahunSKAwal: 2013,
  //     tahunSKAkhir: 2023,
  //     masaKerja: "10 Tahun",
  //     noRegBKN: "1234567890",
  //     jenisTekon: "Tekon A",
  //     kelasJabatan: "Kelas 1",
  //   },
  //   {
  //     id: 8,
  //     no: 8,
  //     foto: "Foto2",
  //     nama: "Jane Smith",
  //     nip: "987654321",
  //     bidang: "HR",
  //     subBidang: "Recruitment",
  //     jabatan: "Staff",
  //     golRuang: "III/b",
  //     jenjang: "S1",
  //     jenis: "PNS",
  //     jenisKelamin: "Perempuan",
  //     tempatLahir: "Bandung",
  //     tanggalLahir: "1992-05-15",
  //     umur: 32,
  //     nik: "6543210987654321",
  //     npwp: "09.876.543.2-109.000",
  //     noRek: "0987654321",
  //     noKK: "6543210987654321",
  //     golDarah: "B",
  //     noHP: "08987654321",
  //     email: "jane.smith@example.com",
  //     emailGov: "jane.smith@gov.com",
  //     pendidikan: "S1",
  //     jurusan: "Psikologi",
  //     tahunTamat: 2014,
  //     jalan: "Jl. Kebangsaan",
  //     desa: "Desa Sejahtera",
  //     kecamatan: "Kecamatan Maju",
  //     kabupatenKota: "Kota Damai",
  //     alamat: "Jl. Kebangsaan No. 2",
  //     tahunSKAwal: 2015,
  //     tahunSKAkhir: 2025,
  //     masaKerja: "8 Tahun",
  //     noRegBKN: "0987654321",
  //     jenisTekon: "Tekon B",
  //     kelasJabatan: "Kelas 2",
  //   },
  //   {
  //     id: 9,
  //     no: 9,
  //     foto: "Foto1",
  //     nama: "John Doe",
  //     nip: "123456789",
  //     bidang: "IT",
  //     subBidang: "Development",
  //     jabatan: "Manager",
  //     golRuang: "IV/a",
  //     jenjang: "S1",
  //     jenis: "PNS",
  //     jenisKelamin: "Laki-laki",
  //     tempatLahir: "Jakarta",
  //     tanggalLahir: "1990-01-01",
  //     umur: 34,
  //     nik: "1234567890123456",
  //     npwp: "01.234.567.8-901.000",
  //     noRek: "1234567890",
  //     noKK: "1234567890123456",
  //     golDarah: "A",
  //     noHP: "08123456789",
  //     email: "john.doe@example.com",
  //     emailGov: "john.doe@gov.com",
  //     pendidikan: "S1",
  //     jurusan: "Informatika",
  //     tahunTamat: 2012,
  //     jalan: "Jl. Merdeka",
  //     desa: "Desa Maju",
  //     kecamatan: "Kecamatan Sejahtera",
  //     kabupatenKota: "Kota Makmur",
  //     alamat: "Jl. Merdeka No. 1",
  //     tahunSKAwal: 2013,
  //     tahunSKAkhir: 2023,
  //     masaKerja: "10 Tahun",
  //     noRegBKN: "1234567890",
  //     jenisTekon: "Tekon A",
  //     kelasJabatan: "Kelas 1",
  //   },
  //   {
  //     id: 10,
  //     no: 10,
  //     foto: "Foto2",
  //     nama: "Jane Smith",
  //     nip: "987654321",
  //     bidang: "HR",
  //     subBidang: "Recruitment",
  //     jabatan: "Staff",
  //     golRuang: "III/b",
  //     jenjang: "S1",
  //     jenis: "PNS",
  //     jenisKelamin: "Perempuan",
  //     tempatLahir: "Bandung",
  //     tanggalLahir: "1992-05-15",
  //     umur: 32,
  //     nik: "6543210987654321",
  //     npwp: "09.876.543.2-109.000",
  //     noRek: "0987654321",
  //     noKK: "6543210987654321",
  //     golDarah: "B",
  //     noHP: "08987654321",
  //     email: "jane.smith@example.com",
  //     emailGov: "jane.smith@gov.com",
  //     pendidikan: "S1",
  //     jurusan: "Psikologi",
  //     tahunTamat: 2014,
  //     jalan: "Jl. Kebangsaan",
  //     desa: "Desa Sejahtera",
  //     kecamatan: "Kecamatan Maju",
  //     kabupatenKota: "Kota Damai",
  //     alamat: "Jl. Kebangsaan No. 2",
  //     tahunSKAwal: 2015,
  //     tahunSKAkhir: 2025,
  //     masaKerja: "8 Tahun",
  //     noRegBKN: "0987654321",
  //     jenisTekon: "Tekon B",
  //     kelasJabatan: "Kelas 2",
  //   },
  //   {
  //     id: 11,
  //     no: 11,
  //     foto: "Foto1",
  //     nama: "John Doe",
  //     nip: "123456789",
  //     bidang: "IT",
  //     subBidang: "Development",
  //     jabatan: "Manager",
  //     golRuang: "IV/a",
  //     jenjang: "S1",
  //     jenis: "PNS",
  //     jenisKelamin: "Laki-laki",
  //     tempatLahir: "Jakarta",
  //     tanggalLahir: "1990-01-01",
  //     umur: 34,
  //     nik: "1234567890123456",
  //     npwp: "01.234.567.8-901.000",
  //     noRek: "1234567890",
  //     noKK: "1234567890123456",
  //     golDarah: "A",
  //     noHP: "08123456789",
  //     email: "john.doe@example.com",
  //     emailGov: "john.doe@gov.com",
  //     pendidikan: "S1",
  //     jurusan: "Informatika",
  //     tahunTamat: 2012,
  //     jalan: "Jl. Merdeka",
  //     desa: "Desa Maju",
  //     kecamatan: "Kecamatan Sejahtera",
  //     kabupatenKota: "Kota Makmur",
  //     alamat: "Jl. Merdeka No. 1",
  //     tahunSKAwal: 2013,
  //     tahunSKAkhir: 2023,
  //     masaKerja: "10 Tahun",
  //     noRegBKN: "1234567890",
  //     jenisTekon: "Tekon A",
  //     kelasJabatan: "Kelas 1",
  //   },
  //   {
  //     id: 12,
  //     no: 12,
  //     foto: "Foto2",
  //     nama: "Jane Smith",
  //     nip: "987654321",
  //     bidang: "HR",
  //     subBidang: "Recruitment",
  //     jabatan: "Staff",
  //     golRuang: "III/b",
  //     jenjang: "S1",
  //     jenis: "PNS",
  //     jenisKelamin: "Perempuan",
  //     tempatLahir: "Bandung",
  //     tanggalLahir: "1992-05-15",
  //     umur: 32,
  //     nik: "6543210987654321",
  //     npwp: "09.876.543.2-109.000",
  //     noRek: "0987654321",
  //     noKK: "6543210987654321",
  //     golDarah: "B",
  //     noHP: "08987654321",
  //     email: "jane.smith@example.com",
  //     emailGov: "jane.smith@gov.com",
  //     pendidikan: "S1",
  //     jurusan: "Psikologi",
  //     tahunTamat: 2014,
  //     jalan: "Jl. Kebangsaan",
  //     desa: "Desa Sejahtera",
  //     kecamatan: "Kecamatan Maju",
  //     kabupatenKota: "Kota Damai",
  //     alamat: "Jl. Kebangsaan No. 2",
  //     tahunSKAwal: 2015,
  //     tahunSKAkhir: 2025,
  //     masaKerja: "8 Tahun",
  //     noRegBKN: "0987654321",
  //     jenisTekon: "Tekon B",
  //     kelasJabatan: "Kelas 2",
  //   },

  //   {
  //     id: 3,
  //     no: 3,
  //     foto: "Foto1",
  //     nama: "John Doe",
  //     nip: "123456789",
  //     bidang: "IT",
  //     subBidang: "Development",
  //     jabatan: "Manager",
  //     golRuang: "IV/a",
  //     jenjang: "S1",
  //     jenis: "PNS",
  //     jenisKelamin: "Laki-laki",
  //     tempatLahir: "Jakarta",
  //     tanggalLahir: "1990-01-01",
  //     umur: 34,
  //     nik: "1234567890123456",
  //     npwp: "01.234.567.8-901.000",
  //     noRek: "1234567890",
  //     noKK: "1234567890123456",
  //     golDarah: "A",
  //     noHP: "08123456789",
  //     email: "john.doe@example.com",
  //     emailGov: "john.doe@gov.com",
  //     pendidikan: "S1",
  //     jurusan: "Informatika",
  //     tahunTamat: 2012,
  //     jalan: "Jl. Merdeka",
  //     desa: "Desa Maju",
  //     kecamatan: "Kecamatan Sejahtera",
  //     kabupatenKota: "Kota Makmur",
  //     alamat: "Jl. Merdeka No. 1",
  //     tahunSKAwal: 2013,
  //     tahunSKAkhir: 2023,
  //     masaKerja: "10 Tahun",
  //     noRegBKN: "1234567890",
  //     jenisTekon: "Tekon A",
  //     kelasJabatan: "Kelas 1",
  //   },
  //   {
  //     id: 4,
  //     no: 4,
  //     foto: "Foto2",
  //     nama: "Jane Smith",
  //     nip: "987654321",
  //     bidang: "HR",
  //     subBidang: "Recruitment",
  //     jabatan: "Staff",
  //     golRuang: "III/b",
  //     jenjang: "S1",
  //     jenis: "PNS",
  //     jenisKelamin: "Perempuan",
  //     tempatLahir: "Bandung",
  //     tanggalLahir: "1992-05-15",
  //     umur: 32,
  //     nik: "6543210987654321",
  //     npwp: "09.876.543.2-109.000",
  //     noRek: "0987654321",
  //     noKK: "6543210987654321",
  //     golDarah: "B",
  //     noHP: "08987654321",
  //     email: "jane.smith@example.com",
  //     emailGov: "jane.smith@gov.com",
  //     pendidikan: "S1",
  //     jurusan: "Psikologi",
  //     tahunTamat: 2014,
  //     jalan: "Jl. Kebangsaan",
  //     desa: "Desa Sejahtera",
  //     kecamatan: "Kecamatan Maju",
  //     kabupatenKota: "Kota Damai",
  //     alamat: "Jl. Kebangsaan No. 2",
  //     tahunSKAwal: 2015,
  //     tahunSKAkhir: 2025,
  //     masaKerja: "8 Tahun",
  //     noRegBKN: "0987654321",
  //     jenisTekon: "Tekon B",
  //     kelasJabatan: "Kelas 2",
  //   },
  //   {
  //     id: 5,
  //     no: 5,
  //     foto: "Foto1",
  //     nama: "John Doe",
  //     nip: "123456789",
  //     bidang: "IT",
  //     subBidang: "Development",
  //     jabatan: "Manager",
  //     golRuang: "IV/a",
  //     jenjang: "S1",
  //     jenis: "PNS",
  //     jenisKelamin: "Laki-laki",
  //     tempatLahir: "Jakarta",
  //     tanggalLahir: "1990-01-01",
  //     umur: 34,
  //     nik: "1234567890123456",
  //     npwp: "01.234.567.8-901.000",
  //     noRek: "1234567890",
  //     noKK: "1234567890123456",
  //     golDarah: "A",
  //     noHP: "08123456789",
  //     email: "john.doe@example.com",
  //     emailGov: "john.doe@gov.com",
  //     pendidikan: "S1",
  //     jurusan: "Informatika",
  //     tahunTamat: 2012,
  //     jalan: "Jl. Merdeka",
  //     desa: "Desa Maju",
  //     kecamatan: "Kecamatan Sejahtera",
  //     kabupatenKota: "Kota Makmur",
  //     alamat: "Jl. Merdeka No. 1",
  //     tahunSKAwal: 2013,
  //     tahunSKAkhir: 2023,
  //     masaKerja: "10 Tahun",
  //     noRegBKN: "1234567890",
  //     jenisTekon: "Tekon A",
  //     kelasJabatan: "Kelas 1",
  //   },
  //   {
  //     id: 6,
  //     no: 6,
  //     foto: "Foto2",
  //     nama: "Jane Smith",
  //     nip: "987654321",
  //     bidang: "HR",
  //     subBidang: "Recruitment",
  //     jabatan: "Staff",
  //     golRuang: "III/b",
  //     jenjang: "S1",
  //     jenis: "PNS",
  //     jenisKelamin: "Perempuan",
  //     tempatLahir: "Bandung",
  //     tanggalLahir: "1992-05-15",
  //     umur: 32,
  //     nik: "6543210987654321",
  //     npwp: "09.876.543.2-109.000",
  //     noRek: "0987654321",
  //     noKK: "6543210987654321",
  //     golDarah: "B",
  //     noHP: "08987654321",
  //     email: "jane.smith@example.com",
  //     emailGov: "jane.smith@gov.com",
  //     pendidikan: "S1",
  //     jurusan: "Psikologi",
  //     tahunTamat: 2014,
  //     jalan: "Jl. Kebangsaan",
  //     desa: "Desa Sejahtera",
  //     kecamatan: "Kecamatan Maju",
  //     kabupatenKota: "Kota Damai",
  //     alamat: "Jl. Kebangsaan No. 2",
  //     tahunSKAwal: 2015,
  //     tahunSKAkhir: 2025,
  //     masaKerja: "8 Tahun",
  //     noRegBKN: "0987654321",
  //     jenisTekon: "Tekon B",
  //     kelasJabatan: "Kelas 2",
  //   },
  //   {
  //     id: 7,
  //     no: 7,
  //     foto: "Foto1",
  //     nama: "John Doe",
  //     nip: "123456789",
  //     bidang: "IT",
  //     subBidang: "Development",
  //     jabatan: "Manager",
  //     golRuang: "IV/a",
  //     jenjang: "S1",
  //     jenis: "PNS",
  //     jenisKelamin: "Laki-laki",
  //     tempatLahir: "Jakarta",
  //     tanggalLahir: "1990-01-01",
  //     umur: 34,
  //     nik: "1234567890123456",
  //     npwp: "01.234.567.8-901.000",
  //     noRek: "1234567890",
  //     noKK: "1234567890123456",
  //     golDarah: "A",
  //     noHP: "08123456789",
  //     email: "john.doe@example.com",
  //     emailGov: "john.doe@gov.com",
  //     pendidikan: "S1",
  //     jurusan: "Informatika",
  //     tahunTamat: 2012,
  //     jalan: "Jl. Merdeka",
  //     desa: "Desa Maju",
  //     kecamatan: "Kecamatan Sejahtera",
  //     kabupatenKota: "Kota Makmur",
  //     alamat: "Jl. Merdeka No. 1",
  //     tahunSKAwal: 2013,
  //     tahunSKAkhir: 2023,
  //     masaKerja: "10 Tahun",
  //     noRegBKN: "1234567890",
  //     jenisTekon: "Tekon A",
  //     kelasJabatan: "Kelas 1",
  //   },
  //   {
  //     id: 8,
  //     no: 8,
  //     foto: "Foto2",
  //     nama: "Jane Smith",
  //     nip: "987654321",
  //     bidang: "HR",
  //     subBidang: "Recruitment",
  //     jabatan: "Staff",
  //     golRuang: "III/b",
  //     jenjang: "S1",
  //     jenis: "PNS",
  //     jenisKelamin: "Perempuan",
  //     tempatLahir: "Bandung",
  //     tanggalLahir: "1992-05-15",
  //     umur: 32,
  //     nik: "6543210987654321",
  //     npwp: "09.876.543.2-109.000",
  //     noRek: "0987654321",
  //     noKK: "6543210987654321",
  //     golDarah: "B",
  //     noHP: "08987654321",
  //     email: "jane.smith@example.com",
  //     emailGov: "jane.smith@gov.com",
  //     pendidikan: "S1",
  //     jurusan: "Psikologi",
  //     tahunTamat: 2014,
  //     jalan: "Jl. Kebangsaan",
  //     desa: "Desa Sejahtera",
  //     kecamatan: "Kecamatan Maju",
  //     kabupatenKota: "Kota Damai",
  //     alamat: "Jl. Kebangsaan No. 2",
  //     tahunSKAwal: 2015,
  //     tahunSKAkhir: 2025,
  //     masaKerja: "8 Tahun",
  //     noRegBKN: "0987654321",
  //     jenisTekon: "Tekon B",
  //     kelasJabatan: "Kelas 2",
  //   },
  //   {
  //     id: 9,
  //     no: 9,
  //     foto: "Foto1",
  //     nama: "John Doe",
  //     nip: "123456789",
  //     bidang: "IT",
  //     subBidang: "Development",
  //     jabatan: "Manager",
  //     golRuang: "IV/a",
  //     jenjang: "S1",
  //     jenis: "PNS",
  //     jenisKelamin: "Laki-laki",
  //     tempatLahir: "Jakarta",
  //     tanggalLahir: "1990-01-01",
  //     umur: 34,
  //     nik: "1234567890123456",
  //     npwp: "01.234.567.8-901.000",
  //     noRek: "1234567890",
  //     noKK: "1234567890123456",
  //     golDarah: "A",
  //     noHP: "08123456789",
  //     email: "john.doe@example.com",
  //     emailGov: "john.doe@gov.com",
  //     pendidikan: "S1",
  //     jurusan: "Informatika",
  //     tahunTamat: 2012,
  //     jalan: "Jl. Merdeka",
  //     desa: "Desa Maju",
  //     kecamatan: "Kecamatan Sejahtera",
  //     kabupatenKota: "Kota Makmur",
  //     alamat: "Jl. Merdeka No. 1",
  //     tahunSKAwal: 2013,
  //     tahunSKAkhir: 2023,
  //     masaKerja: "10 Tahun",
  //     noRegBKN: "1234567890",
  //     jenisTekon: "Tekon A",
  //     kelasJabatan: "Kelas 1",
  //   },
  //   {
  //     id: 10,
  //     no: 10,
  //     foto: "Foto2",
  //     nama: "Jane Smith",
  //     nip: "987654321",
  //     bidang: "HR",
  //     subBidang: "Recruitment",
  //     jabatan: "Staff",
  //     golRuang: "III/b",
  //     jenjang: "S1",
  //     jenis: "PNS",
  //     jenisKelamin: "Perempuan",
  //     tempatLahir: "Bandung",
  //     tanggalLahir: "1992-05-15",
  //     umur: 32,
  //     nik: "6543210987654321",
  //     npwp: "09.876.543.2-109.000",
  //     noRek: "0987654321",
  //     noKK: "6543210987654321",
  //     golDarah: "B",
  //     noHP: "08987654321",
  //     email: "jane.smith@example.com",
  //     emailGov: "jane.smith@gov.com",
  //     pendidikan: "S1",
  //     jurusan: "Psikologi",
  //     tahunTamat: 2014,
  //     jalan: "Jl. Kebangsaan",
  //     desa: "Desa Sejahtera",
  //     kecamatan: "Kecamatan Maju",
  //     kabupatenKota: "Kota Damai",
  //     alamat: "Jl. Kebangsaan No. 2",
  //     tahunSKAwal: 2015,
  //     tahunSKAkhir: 2025,
  //     masaKerja: "8 Tahun",
  //     noRegBKN: "0987654321",
  //     jenisTekon: "Tekon B",
  //     kelasJabatan: "Kelas 2",
  //   },
  //   {
  //     id: 11,
  //     no: 11,
  //     foto: "Foto1",
  //     nama: "John Doe",
  //     nip: "123456789",
  //     bidang: "IT",
  //     subBidang: "Development",
  //     jabatan: "Manager",
  //     golRuang: "IV/a",
  //     jenjang: "S1",
  //     jenis: "PNS",
  //     jenisKelamin: "Laki-laki",
  //     tempatLahir: "Jakarta",
  //     tanggalLahir: "1990-01-01",
  //     umur: 34,
  //     nik: "1234567890123456",
  //     npwp: "01.234.567.8-901.000",
  //     noRek: "1234567890",
  //     noKK: "1234567890123456",
  //     golDarah: "A",
  //     noHP: "08123456789",
  //     email: "john.doe@example.com",
  //     emailGov: "john.doe@gov.com",
  //     pendidikan: "S1",
  //     jurusan: "Informatika",
  //     tahunTamat: 2012,
  //     jalan: "Jl. Merdeka",
  //     desa: "Desa Maju",
  //     kecamatan: "Kecamatan Sejahtera",
  //     kabupatenKota: "Kota Makmur",
  //     alamat: "Jl. Merdeka No. 1",
  //     tahunSKAwal: 2013,
  //     tahunSKAkhir: 2023,
  //     masaKerja: "10 Tahun",
  //     noRegBKN: "1234567890",
  //     jenisTekon: "Tekon A",
  //     kelasJabatan: "Kelas 1",
  //   },
  //   {
  //     id: 12,
  //     no: 12,
  //     foto: "Foto2",
  //     nama: "Jane Smith",
  //     nip: "987654321",
  //     bidang: "HR",
  //     subBidang: "Recruitment",
  //     jabatan: "Staff",
  //     golRuang: "III/b",
  //     jenjang: "S1",
  //     jenis: "PNS",
  //     jenisKelamin: "Perempuan",
  //     tempatLahir: "Bandung",
  //     tanggalLahir: "1992-05-15",
  //     umur: 32,
  //     nik: "6543210987654321",
  //     npwp: "09.876.543.2-109.000",
  //     noRek: "0987654321",
  //     noKK: "6543210987654321",
  //     golDarah: "B",
  //     noHP: "08987654321",
  //     email: "jane.smith@example.com",
  //     emailGov: "jane.smith@gov.com",
  //     pendidikan: "S1",
  //     jurusan: "Psikologi",
  //     tahunTamat: 2014,
  //     jalan: "Jl. Kebangsaan",
  //     desa: "Desa Sejahtera",
  //     kecamatan: "Kecamatan Maju",
  //     kabupatenKota: "Kota Damai",
  //     alamat: "Jl. Kebangsaan No. 2",
  //     tahunSKAwal: 2015,
  //     tahunSKAkhir: 2025,
  //     masaKerja: "8 Tahun",
  //     noRegBKN: "0987654321",
  //     jenisTekon: "Tekon B",
  //     kelasJabatan: "Kelas 2",
  //   },

  //   {
  //     id: 3,
  //     no: 3,
  //     foto: "Foto1",
  //     nama: "John Doe",
  //     nip: "123456789",
  //     bidang: "IT",
  //     subBidang: "Development",
  //     jabatan: "Manager",
  //     golRuang: "IV/a",
  //     jenjang: "S1",
  //     jenis: "PNS",
  //     jenisKelamin: "Laki-laki",
  //     tempatLahir: "Jakarta",
  //     tanggalLahir: "1990-01-01",
  //     umur: 34,
  //     nik: "1234567890123456",
  //     npwp: "01.234.567.8-901.000",
  //     noRek: "1234567890",
  //     noKK: "1234567890123456",
  //     golDarah: "A",
  //     noHP: "08123456789",
  //     email: "john.doe@example.com",
  //     emailGov: "john.doe@gov.com",
  //     pendidikan: "S1",
  //     jurusan: "Informatika",
  //     tahunTamat: 2012,
  //     jalan: "Jl. Merdeka",
  //     desa: "Desa Maju",
  //     kecamatan: "Kecamatan Sejahtera",
  //     kabupatenKota: "Kota Makmur",
  //     alamat: "Jl. Merdeka No. 1",
  //     tahunSKAwal: 2013,
  //     tahunSKAkhir: 2023,
  //     masaKerja: "10 Tahun",
  //     noRegBKN: "1234567890",
  //     jenisTekon: "Tekon A",
  //     kelasJabatan: "Kelas 1",
  //   },
  //   {
  //     id: 4,
  //     no: 4,
  //     foto: "Foto2",
  //     nama: "Jane Smith",
  //     nip: "987654321",
  //     bidang: "HR",
  //     subBidang: "Recruitment",
  //     jabatan: "Staff",
  //     golRuang: "III/b",
  //     jenjang: "S1",
  //     jenis: "PNS",
  //     jenisKelamin: "Perempuan",
  //     tempatLahir: "Bandung",
  //     tanggalLahir: "1992-05-15",
  //     umur: 32,
  //     nik: "6543210987654321",
  //     npwp: "09.876.543.2-109.000",
  //     noRek: "0987654321",
  //     noKK: "6543210987654321",
  //     golDarah: "B",
  //     noHP: "08987654321",
  //     email: "jane.smith@example.com",
  //     emailGov: "jane.smith@gov.com",
  //     pendidikan: "S1",
  //     jurusan: "Psikologi",
  //     tahunTamat: 2014,
  //     jalan: "Jl. Kebangsaan",
  //     desa: "Desa Sejahtera",
  //     kecamatan: "Kecamatan Maju",
  //     kabupatenKota: "Kota Damai",
  //     alamat: "Jl. Kebangsaan No. 2",
  //     tahunSKAwal: 2015,
  //     tahunSKAkhir: 2025,
  //     masaKerja: "8 Tahun",
  //     noRegBKN: "0987654321",
  //     jenisTekon: "Tekon B",
  //     kelasJabatan: "Kelas 2",
  //   },
  //   {
  //     id: 5,
  //     no: 5,
  //     foto: "Foto1",
  //     nama: "John Doe",
  //     nip: "123456789",
  //     bidang: "IT",
  //     subBidang: "Development",
  //     jabatan: "Manager",
  //     golRuang: "IV/a",
  //     jenjang: "S1",
  //     jenis: "PNS",
  //     jenisKelamin: "Laki-laki",
  //     tempatLahir: "Jakarta",
  //     tanggalLahir: "1990-01-01",
  //     umur: 34,
  //     nik: "1234567890123456",
  //     npwp: "01.234.567.8-901.000",
  //     noRek: "1234567890",
  //     noKK: "1234567890123456",
  //     golDarah: "A",
  //     noHP: "08123456789",
  //     email: "john.doe@example.com",
  //     emailGov: "john.doe@gov.com",
  //     pendidikan: "S1",
  //     jurusan: "Informatika",
  //     tahunTamat: 2012,
  //     jalan: "Jl. Merdeka",
  //     desa: "Desa Maju",
  //     kecamatan: "Kecamatan Sejahtera",
  //     kabupatenKota: "Kota Makmur",
  //     alamat: "Jl. Merdeka No. 1",
  //     tahunSKAwal: 2013,
  //     tahunSKAkhir: 2023,
  //     masaKerja: "10 Tahun",
  //     noRegBKN: "1234567890",
  //     jenisTekon: "Tekon A",
  //     kelasJabatan: "Kelas 1",
  //   },
  //   {
  //     id: 6,
  //     no: 6,
  //     foto: "Foto2",
  //     nama: "Jane Smith",
  //     nip: "987654321",
  //     bidang: "HR",
  //     subBidang: "Recruitment",
  //     jabatan: "Staff",
  //     golRuang: "III/b",
  //     jenjang: "S1",
  //     jenis: "PNS",
  //     jenisKelamin: "Perempuan",
  //     tempatLahir: "Bandung",
  //     tanggalLahir: "1992-05-15",
  //     umur: 32,
  //     nik: "6543210987654321",
  //     npwp: "09.876.543.2-109.000",
  //     noRek: "0987654321",
  //     noKK: "6543210987654321",
  //     golDarah: "B",
  //     noHP: "08987654321",
  //     email: "jane.smith@example.com",
  //     emailGov: "jane.smith@gov.com",
  //     pendidikan: "S1",
  //     jurusan: "Psikologi",
  //     tahunTamat: 2014,
  //     jalan: "Jl. Kebangsaan",
  //     desa: "Desa Sejahtera",
  //     kecamatan: "Kecamatan Maju",
  //     kabupatenKota: "Kota Damai",
  //     alamat: "Jl. Kebangsaan No. 2",
  //     tahunSKAwal: 2015,
  //     tahunSKAkhir: 2025,
  //     masaKerja: "8 Tahun",
  //     noRegBKN: "0987654321",
  //     jenisTekon: "Tekon B",
  //     kelasJabatan: "Kelas 2",
  //   },
  //   {
  //     id: 7,
  //     no: 7,
  //     foto: "Foto1",
  //     nama: "John Doe",
  //     nip: "123456789",
  //     bidang: "IT",
  //     subBidang: "Development",
  //     jabatan: "Manager",
  //     golRuang: "IV/a",
  //     jenjang: "S1",
  //     jenis: "PNS",
  //     jenisKelamin: "Laki-laki",
  //     tempatLahir: "Jakarta",
  //     tanggalLahir: "1990-01-01",
  //     umur: 34,
  //     nik: "1234567890123456",
  //     npwp: "01.234.567.8-901.000",
  //     noRek: "1234567890",
  //     noKK: "1234567890123456",
  //     golDarah: "A",
  //     noHP: "08123456789",
  //     email: "john.doe@example.com",
  //     emailGov: "john.doe@gov.com",
  //     pendidikan: "S1",
  //     jurusan: "Informatika",
  //     tahunTamat: 2012,
  //     jalan: "Jl. Merdeka",
  //     desa: "Desa Maju",
  //     kecamatan: "Kecamatan Sejahtera",
  //     kabupatenKota: "Kota Makmur",
  //     alamat: "Jl. Merdeka No. 1",
  //     tahunSKAwal: 2013,
  //     tahunSKAkhir: 2023,
  //     masaKerja: "10 Tahun",
  //     noRegBKN: "1234567890",
  //     jenisTekon: "Tekon A",
  //     kelasJabatan: "Kelas 1",
  //   },
  //   {
  //     id: 8,
  //     no: 8,
  //     foto: "Foto2",
  //     nama: "Jane Smith",
  //     nip: "987654321",
  //     bidang: "HR",
  //     subBidang: "Recruitment",
  //     jabatan: "Staff",
  //     golRuang: "III/b",
  //     jenjang: "S1",
  //     jenis: "PNS",
  //     jenisKelamin: "Perempuan",
  //     tempatLahir: "Bandung",
  //     tanggalLahir: "1992-05-15",
  //     umur: 32,
  //     nik: "6543210987654321",
  //     npwp: "09.876.543.2-109.000",
  //     noRek: "0987654321",
  //     noKK: "6543210987654321",
  //     golDarah: "B",
  //     noHP: "08987654321",
  //     email: "jane.smith@example.com",
  //     emailGov: "jane.smith@gov.com",
  //     pendidikan: "S1",
  //     jurusan: "Psikologi",
  //     tahunTamat: 2014,
  //     jalan: "Jl. Kebangsaan",
  //     desa: "Desa Sejahtera",
  //     kecamatan: "Kecamatan Maju",
  //     kabupatenKota: "Kota Damai",
  //     alamat: "Jl. Kebangsaan No. 2",
  //     tahunSKAwal: 2015,
  //     tahunSKAkhir: 2025,
  //     masaKerja: "8 Tahun",
  //     noRegBKN: "0987654321",
  //     jenisTekon: "Tekon B",
  //     kelasJabatan: "Kelas 2",
  //   },
  //   {
  //     id: 9,
  //     no: 9,
  //     foto: "Foto1",
  //     nama: "John Doe",
  //     nip: "123456789",
  //     bidang: "IT",
  //     subBidang: "Development",
  //     jabatan: "Manager",
  //     golRuang: "IV/a",
  //     jenjang: "S1",
  //     jenis: "PNS",
  //     jenisKelamin: "Laki-laki",
  //     tempatLahir: "Jakarta",
  //     tanggalLahir: "1990-01-01",
  //     umur: 34,
  //     nik: "1234567890123456",
  //     npwp: "01.234.567.8-901.000",
  //     noRek: "1234567890",
  //     noKK: "1234567890123456",
  //     golDarah: "A",
  //     noHP: "08123456789",
  //     email: "john.doe@example.com",
  //     emailGov: "john.doe@gov.com",
  //     pendidikan: "S1",
  //     jurusan: "Informatika",
  //     tahunTamat: 2012,
  //     jalan: "Jl. Merdeka",
  //     desa: "Desa Maju",
  //     kecamatan: "Kecamatan Sejahtera",
  //     kabupatenKota: "Kota Makmur",
  //     alamat: "Jl. Merdeka No. 1",
  //     tahunSKAwal: 2013,
  //     tahunSKAkhir: 2023,
  //     masaKerja: "10 Tahun",
  //     noRegBKN: "1234567890",
  //     jenisTekon: "Tekon A",
  //     kelasJabatan: "Kelas 1",
  //   },
  //   {
  //     id: 10,
  //     no: 10,
  //     foto: "Foto2",
  //     nama: "Jane Smith",
  //     nip: "987654321",
  //     bidang: "HR",
  //     subBidang: "Recruitment",
  //     jabatan: "Staff",
  //     golRuang: "III/b",
  //     jenjang: "S1",
  //     jenis: "PNS",
  //     jenisKelamin: "Perempuan",
  //     tempatLahir: "Bandung",
  //     tanggalLahir: "1992-05-15",
  //     umur: 32,
  //     nik: "6543210987654321",
  //     npwp: "09.876.543.2-109.000",
  //     noRek: "0987654321",
  //     noKK: "6543210987654321",
  //     golDarah: "B",
  //     noHP: "08987654321",
  //     email: "jane.smith@example.com",
  //     emailGov: "jane.smith@gov.com",
  //     pendidikan: "S1",
  //     jurusan: "Psikologi",
  //     tahunTamat: 2014,
  //     jalan: "Jl. Kebangsaan",
  //     desa: "Desa Sejahtera",
  //     kecamatan: "Kecamatan Maju",
  //     kabupatenKota: "Kota Damai",
  //     alamat: "Jl. Kebangsaan No. 2",
  //     tahunSKAwal: 2015,
  //     tahunSKAkhir: 2025,
  //     masaKerja: "8 Tahun",
  //     noRegBKN: "0987654321",
  //     jenisTekon: "Tekon B",
  //     kelasJabatan: "Kelas 2",
  //   },
  //   {
  //     id: 11,
  //     no: 11,
  //     foto: "Foto1",
  //     nama: "John Doe",
  //     nip: "123456789",
  //     bidang: "IT",
  //     subBidang: "Development",
  //     jabatan: "Manager",
  //     golRuang: "IV/a",
  //     jenjang: "S1",
  //     jenis: "PNS",
  //     jenisKelamin: "Laki-laki",
  //     tempatLahir: "Jakarta",
  //     tanggalLahir: "1990-01-01",
  //     umur: 34,
  //     nik: "1234567890123456",
  //     npwp: "01.234.567.8-901.000",
  //     noRek: "1234567890",
  //     noKK: "1234567890123456",
  //     golDarah: "A",
  //     noHP: "08123456789",
  //     email: "john.doe@example.com",
  //     emailGov: "john.doe@gov.com",
  //     pendidikan: "S1",
  //     jurusan: "Informatika",
  //     tahunTamat: 2012,
  //     jalan: "Jl. Merdeka",
  //     desa: "Desa Maju",
  //     kecamatan: "Kecamatan Sejahtera",
  //     kabupatenKota: "Kota Makmur",
  //     alamat: "Jl. Merdeka No. 1",
  //     tahunSKAwal: 2013,
  //     tahunSKAkhir: 2023,
  //     masaKerja: "10 Tahun",
  //     noRegBKN: "1234567890",
  //     jenisTekon: "Tekon A",
  //     kelasJabatan: "Kelas 1",
  //   },
  //   {
  //     id: 12,
  //     no: 12,
  //     foto: "Foto2",
  //     nama: "Jane Smith",
  //     nip: "987654321",
  //     bidang: "HR",
  //     subBidang: "Recruitment",
  //     jabatan: "Staff",
  //     golRuang: "III/b",
  //     jenjang: "S1",
  //     jenis: "PNS",
  //     jenisKelamin: "Perempuan",
  //     tempatLahir: "Bandung",
  //     tanggalLahir: "1992-05-15",
  //     umur: 32,
  //     nik: "6543210987654321",
  //     npwp: "09.876.543.2-109.000",
  //     noRek: "0987654321",
  //     noKK: "6543210987654321",
  //     golDarah: "B",
  //     noHP: "08987654321",
  //     email: "jane.smith@example.com",
  //     emailGov: "jane.smith@gov.com",
  //     pendidikan: "S1",
  //     jurusan: "Psikologi",
  //     tahunTamat: 2014,
  //     jalan: "Jl. Kebangsaan",
  //     desa: "Desa Sejahtera",
  //     kecamatan: "Kecamatan Maju",
  //     kabupatenKota: "Kota Damai",
  //     alamat: "Jl. Kebangsaan No. 2",
  //     tahunSKAwal: 2015,
  //     tahunSKAkhir: 2025,
  //     masaKerja: "8 Tahun",
  //     noRegBKN: "0987654321",
  //     jenisTekon: "Tekon B",
  //     kelasJabatan: "Kelas 2",
  //   },
  // ];

  // const handleEdit = (id) => {
  //   console.log(`Edit row with id: ${id}`);
  //   // Implement edit functionality
  // };

  // const handleDelete = (id) => {
  //   console.log(`Delete row with id: ${id}`);
  //   // Implement delete functionality
  // };

  const [records, setRecords] = useState();

  // function handleFilter(event) {
  //   const newData = fetchData.filter((row) => {
  //     return row.nama.toLowerCase().includes(event.target.value.toLowerCase());
  //   });
  //   setRecords(newData);
  // }

  return (
    <div className="min-h-screen">
      <main className="py-8">
        <div className="mx-auto sm:px-6 lg:px-8">
          {/* Konten Dashboard */}
          <div className="bg-white shadow overflow-hidden sm:rounded-lg p-6">
            <h1 className="text-2xl font-bold">Data Karyawan</h1>
            <div className="container mt-8">
              <div className="flex flex-row justify-between items-center mb-4">
                <button
                  className="bg-custom-blue text-white px-4 py-2 rounded hover:bg-blue-700"
                >
                  Tambah Data
                </button>
                <div className="flex basis-1/3 items-center space-x-4">
                  <p className="font-semibold">Search:</p>
                  <input
                    type="text"
                    className="border border-gray-300 rounded-md p-2 w-full"
                    // onChange={handleFilter}
                    placeholder="Filter by Name"
                  />
                  <div className="flex justify-center items-center space-x-2">
                    <FaEdit
                      className=" hover:bg-blue-700 bg-custom-blue fill-white hover:text-custom-blue cursor-pointer rounded-xl p-2 transition duration-300 ease-in-out"
                      size={36}
                    />
                    <FaTrash
                      className=" hover:bg-blue-700 bg-custom-blue fill-white hover:text-custom-blue cursor-pointer rounded-xl  p-2 transition duration-300 ease-in-out"
                      size={36}
                    />
                  </div>
                </div>
              </div>
              <DataTable
                columns={columns}
                data={records}
                customStyles={customStyles}
                selectableRows
                fixedHeader
                pagination
              />
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default DataKaryawan;
